### ISSUE TITLE
Spelling Mistake

### ISSUE THREAD

**Issue by sancharibansal** [Tejashri-Taral/TrendTrove-Ecommerce#199]
In nav bar, in products section, its written **"mens and womens"**, which will create a bad impact on the user/customer.
Here's the screenshot.

<img width="1440" alt="Screenshot 2024-10-07 at 4 48 17 AM" src="https://github.com/user-attachments/assets/e2ba75ca-d238-450e-89aa-a681ae49d647">

@Tejashri-Taral 
I would like to fix this.

**Comment by Bhumika-00** [comment]
With my great communication skills I can improve the overall quality of English used as well as make it more attractive for audience

**Comment by Deepikajyothi007** [comment]
I would like to fix this

**Comment by Tejashri-Taral** [comment]
@sancharibansal 
As this task is not sufficient for giving level1 
So I'm adding an extra task for you - 
Improve the styling of that drop-down on products link do that there will be an up-down arrow on hovering. Also those men's and women's link will be appearing in a squared box structurally

Let me know if you can do it.
Because I can't give level1 for spelling correction as it is not a contribution

**Comment by Deepikajyothi007** [comment]
Okay I'll do it @Tejashri-Taral

**Comment by sancharibansal** [comment]
Okay @Tejashri-Taral, I've started working on it
Thanks for assigning it to me

**Comment by himanchal08** [comment]
Hi @Tejashri-Taral ,

Could you please assign this issue to me? I would love to work on it.
I offer some spelling changes and some styling updates too. Also improving the mobile view of the website . 

Thank you!
Himanchal
